# Generated by Django 4.0 on 2022-07-21 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestorProveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=25, unique=True)),
                ('hexadecimal', models.CharField(blank=True, max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25, null=True)),
                ('price_buy', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(500.0)])),
                ('price_suggest', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(500.0)])),
                ('entire_stock', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('belong_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestorProveedor.proveedor')),
                ('colors', models.ManyToManyField(to='gestorZapatilla.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_zapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(45.0)])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('general_zapatilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestorZapatilla.zapatilla')),
            ],
        ),
    ]
